version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=code_challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  code_challenge:
    build:
      context: ../
    depends_on:
      - postgres
    image: code_challenge
    ports:
      - "8080:8080"
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://postgres:5432/code_challenge
      - spring.liquibase.url=jdbc:postgresql://postgres:5432/code_challenge
      - spring.liquibase.user=admin
      - spring.liquibase.password=password

volumes:
  postgres_data: